Feature order
fvv-vasquez/prj-jse-bookstore pull request #10
Opened 2018-04-22 16:09 UTC by fvv-vasquez

Order and Order Item classes.

2018-04-22 16:35 UTC, cssantos0 commented
add a proper msg when inserting dvd to know how is the format in the duration field

2018-04-22 16:40 UTC, cssantos0 commented
please make it easier when adding a DVD by accepting lower case in type

2018-04-22 16:44 UTC, cssantos0 commented
when adding a cellphone specify in the "brand" message to also put the model

2018-04-22 17:19 UTC, cssantos0 commented
make sure all calculations round the double value to 2 precision units (round when necessary)

2018-04-22 18:18 UTC, cssantos0 requested changes
@fvv-vasquez the application is working correclty, good job there. Although you have several points to refactor in the code

2018-04-22 18:18 UTC, cssantos0 commented on sql/bookstore_db.sql
> +-- --------------------------------------------------------
please add a new file w/ inserts to load data

2018-04-22 18:18 UTC, cssantos0 commented on src/main/java/com/fvv/bookstore/bean/Order.java
> +	private Date date;
please change the name to `creationDate`

2018-04-22 18:18 UTC, cssantos0 commented on src/main/java/com/fvv/bookstore/bean/Product.java
> +
remove the `public` from constructor in abstract classes, since it can be private-package

2018-04-22 18:18 UTC, cssantos0 commented on src/main/java/com/fvv/bookstore/dao/BookDAOImpl.java
> +						book.setId(rs.getLong("book_id"));
all property set can be refactored in a separated method since you have duplicated code in both find method

2018-04-22 18:18 UTC, cssantos0 commented on src/main/java/com/fvv/bookstore/dao/CellphoneDAOImpl.java
> +						cellphone.setId(rs.getLong("cel_id"));
all property set can be refactored in a separated method since you have duplicated code in both find method

2018-04-22 18:18 UTC, cssantos0 commented on src/main/java/com/fvv/bookstore/dao/DvdDAOImpl.java
> +						}
all property set can be refactored in a separated method since you have duplicated code in both find method

2018-04-22 18:18 UTC, cssantos0 commented on src/main/java/com/fvv/bookstore/dao/LaptopDAOImpl.java
> +						laptop.setId(rs.getLong("pc_id"));
all property set can be refactored in a separated method since you have duplicated code in both find method

2018-04-22 18:18 UTC, cssantos0 commented on src/main/java/com/fvv/bookstore/dao/MagazineDAOImpl.java
> +					do {
all property set can be refactored in a separated method since you have duplicated code in both find method

2018-04-22 18:18 UTC, cssantos0 commented on src/main/java/com/fvv/bookstore/dao/OrderDAOImpl.java
> +	private final OrderItemDAO ordemItemDao;
should be named orderItemDao

2018-04-22 18:18 UTC, cssantos0 commented on src/main/java/com/fvv/bookstore/dao/OrderDAOImpl.java
> +			Long orderPK = this.getPrimaryKey(ps);
can be final

2018-04-22 18:18 UTC, cssantos0 commented on src/main/java/com/fvv/bookstore/dao/OrderDAOImpl.java
> +	 * @param ps of PreparedStament type.
typo

2018-04-22 18:18 UTC, cssantos0 commented on src/main/java/com/fvv/bookstore/dao/OrderItemDAO.java
> +	 * Add order items at the bookstore in the database.
elaborate a better doc

2018-04-22 18:18 UTC, cssantos0 commented on src/main/java/com/fvv/bookstore/dao/OrderItemDAO.java
> +	 * @param ordemItems of List<OrderItem> type.
wrong param name

2018-04-22 18:18 UTC, cssantos0 commented on src/main/java/com/fvv/bookstore/controller/OrderControllerImpl.java
> +	private String validateOrderItem(final List<OrderItem> orderItems) throws OrderValidationException {
remove the not used exception

2018-04-22 18:18 UTC, cssantos0 commented on src/main/java/com/fvv/bookstore/controller/OrderControllerImpl.java
> +	private Integer calculateStockAmount(final Product product, final Integer quantityBougth) {
typo in bought

2018-04-22 18:18 UTC, cssantos0 commented on src/main/java/com/fvv/bookstore/controller/OrderControllerImpl.java
> +	private Integer calculateStockAmount(final Product product, final Integer quantityBougth) {
you dont need a product here, just an integer representing the currentStockAmount.

2018-04-22 18:18 UTC, cssantos0 commented on src/main/java/com/fvv/bookstore/controller/OrderControllerImpl.java
> +	 * Validate if a field is empty.
improve the javadoc message

2018-04-22 18:18 UTC, cssantos0 commented on src/main/java/com/fvv/bookstore/controller/OrderControllerImpl.java
> +	 * Validate if a field is empty.
improve the javadoc message

2018-04-22 18:18 UTC, cssantos0 commented on src/main/java/com/fvv/bookstore/controller/OrderControllerImpl.java
> +				sb.append("Stock quantity 0").append(Constants.LINE_SEPARATOR);
improve this message

2018-04-22 18:18 UTC, cssantos0 commented on src/main/java/com/fvv/bookstore/controller/OrderControllerImpl.java
> +			Integer newStockQty = this.calculateStockAmount(items.getProduct(), items.getQuantity());
it can be final

2018-04-22 18:18 UTC, cssantos0 commented on src/main/java/com/fvv/bookstore/view/OrderViewImpl.java
> +		final List<OrderItem> items = new ArrayList<OrderItem>();
use `final List<OrderItem> items = new ArrayList<>();`

2018-04-22 18:18 UTC, cssantos0 commented on src/main/java/com/fvv/bookstore/view/OrderViewImpl.java
> +	private List<OrderItem> createOrderItemFromInput() throws ControllerException {
you can remove the exception

2018-04-22 18:18 UTC, cssantos0 commented on src/main/java/com/fvv/bookstore/view/OrderViewImpl.java
> +			final Book book = this.bookController.findBookByTitle(
This variable is redundant

2018-04-22 18:18 UTC, cssantos0 commented on src/main/java/com/fvv/bookstore/view/OrderViewImpl.java
> +			final Cellphone cellphone = this.cellphoneController.findCellphoneByBrand(
This variable is redundant

2018-04-22 18:18 UTC, cssantos0 commented on src/main/java/com/fvv/bookstore/view/OrderViewImpl.java
> +			final Dvd dvd = this.dvdController.findDvdByTitle(
This variable is redundant

2018-04-22 18:18 UTC, cssantos0 commented on src/main/java/com/fvv/bookstore/view/OrderViewImpl.java
> +			final Laptop laptop = this.laptopController.findLaptopByBrand(
This variable is redundant

2018-04-22 18:18 UTC, cssantos0 commented on src/main/java/com/fvv/bookstore/view/OrderViewImpl.java
> +			final Magazine magazine = this.magazineController.findMagazineByName(
This variable is redundant

2018-04-22 18:18 UTC, cssantos0 commented on src/main/java/com/fvv/bookstore/view/OrderViewImpl.java
> +	private Magazine findMagazineByName() {
add a string param representing the value to look up and then pass the joptionPane wherever you're calling this method

2018-04-22 18:18 UTC, cssantos0 commented on src/main/java/com/fvv/bookstore/view/OrderViewImpl.java
> +	private Laptop findLaptopByBrand() {
add a string param representing the value to look up and then pass the joptionPane wherever you're calling this method

2018-04-22 18:18 UTC, cssantos0 commented on src/main/java/com/fvv/bookstore/view/OrderViewImpl.java
> +	private Dvd findDvdByTitle() {
add a string param representing the value to look up and then pass the joptionPane wherever you're calling this method

2018-04-22 18:18 UTC, cssantos0 commented on src/main/java/com/fvv/bookstore/view/OrderViewImpl.java
> +	private Cellphone findCellphoneByBrand() {
add a string param representing the value to look up and then pass the joptionPane wherever you're calling this method

2018-04-22 18:18 UTC, cssantos0 commented on src/main/java/com/fvv/bookstore/view/OrderViewImpl.java
> +	private Book findBookByTitle() {
add a string param representing the value to look up and then pass the joptionPane wherever you're calling this method

2018-04-22 18:18 UTC, cssantos0 commented on src/main/java/com/fvv/bookstore/view/OrderViewImpl.java
> +	 * @return a boolean.
improve this message

2018-04-22 18:18 UTC, cssantos0 commented on src/main/java/com/fvv/bookstore/view/OrderViewImpl.java
> +	 * @param items of List<OrderItem> type.
you dont need the return type here, it is better to use a message to help to understand what is needed to pass it

2018-04-22 18:18 UTC, cssantos0 commented on src/main/java/com/fvv/bookstore/view/OrderViewImpl.java
> +	private List<OrderItem> createOrderItemFromInput() throws ControllerException {
its better to call it createOrderItemsFromInput

2018-04-22 18:18 UTC, cssantos0 commented on src/main/java/com/fvv/bookstore/view/OrderViewImpl.java
> +							if(book.getStockQty() > 0) {
isolate the similar implementation in a method to reduce the amount of duplicates

2018-04-22 20:14 UTC, fvv-vasquez commented on src/main/java/com/fvv/bookstore/bean/Order.java
> +	private Date date;
ok

2018-04-22 20:16 UTC, fvv-vasquez commented on src/main/java/com/fvv/bookstore/bean/Product.java
> +
ok

2018-04-22 20:39 UTC, fvv-vasquez commented on src/main/java/com/fvv/bookstore/dao/BookDAOImpl.java
> +						book.setId(rs.getLong("book_id"));
ok

2018-04-22 20:39 UTC, fvv-vasquez commented on src/main/java/com/fvv/bookstore/dao/CellphoneDAOImpl.java
> +						cellphone.setId(rs.getLong("cel_id"));
ok

2018-04-22 20:39 UTC, fvv-vasquez commented on src/main/java/com/fvv/bookstore/dao/DvdDAOImpl.java
> +						}
ok

2018-04-22 20:42 UTC, fvv-vasquez commented on src/main/java/com/fvv/bookstore/dao/LaptopDAOImpl.java
> +						laptop.setId(rs.getLong("pc_id"));
ok

2018-04-22 20:44 UTC, fvv-vasquez commented on src/main/java/com/fvv/bookstore/dao/MagazineDAOImpl.java
> +					do {
ok

2018-04-29 16:04 UTC, fvv-vasquez commented on src/main/java/com/fvv/bookstore/dao/OrderDAOImpl.java
> +	private final OrderItemDAO ordemItemDao;
ok

2018-04-29 16:07 UTC, fvv-vasquez commented on src/main/java/com/fvv/bookstore/dao/OrderDAOImpl.java
> +			Long orderPK = this.getPrimaryKey(ps);
ok

2018-04-29 16:08 UTC, fvv-vasquez commented on src/main/java/com/fvv/bookstore/dao/OrderDAOImpl.java
> +	 * @param ps of PreparedStament type.
ok

2018-04-29 16:10 UTC, fvv-vasquez commented on src/main/java/com/fvv/bookstore/dao/OrderItemDAO.java
> +	 * @param ordemItems of List<OrderItem> type.
ok

2018-04-29 16:12 UTC, fvv-vasquez commented on src/main/java/com/fvv/bookstore/dao/OrderItemDAO.java
> +	 * Add order items at the bookstore in the database.
ok

2018-04-29 16:14 UTC, fvv-vasquez commented on src/main/java/com/fvv/bookstore/controller/OrderControllerImpl.java
> +	private String validateOrderItem(final List<OrderItem> orderItems) throws OrderValidationException {
ok

2018-04-29 16:15 UTC, fvv-vasquez commented on src/main/java/com/fvv/bookstore/controller/OrderControllerImpl.java
> +	private Integer calculateStockAmount(final Product product, final Integer quantityBougth) {
ok

2018-04-29 16:19 UTC, fvv-vasquez commented on src/main/java/com/fvv/bookstore/controller/OrderControllerImpl.java
> +	private Integer calculateStockAmount(final Product product, final Integer quantityBougth) {
ok

2018-04-29 16:20 UTC, fvv-vasquez commented on src/main/java/com/fvv/bookstore/controller/OrderControllerImpl.java
> +	 * Validate if a field is empty.
ok

2018-04-29 16:21 UTC, fvv-vasquez commented on src/main/java/com/fvv/bookstore/controller/OrderControllerImpl.java
> +	 * Validate if a field is empty.
ok

2018-04-29 16:23 UTC, fvv-vasquez commented on src/main/java/com/fvv/bookstore/controller/OrderControllerImpl.java
> +				sb.append("Stock quantity 0").append(Constants.LINE_SEPARATOR);
ok

2018-04-29 16:24 UTC, fvv-vasquez commented on src/main/java/com/fvv/bookstore/controller/OrderControllerImpl.java
> +			Integer newStockQty = this.calculateStockAmount(items.getProduct(), items.getQuantity());
ok

2018-04-29 16:25 UTC, fvv-vasquez commented on src/main/java/com/fvv/bookstore/view/OrderViewImpl.java
> +	private List<OrderItem> createOrderItemFromInput() throws ControllerException {
ok

2018-04-29 16:27 UTC, fvv-vasquez commented on src/main/java/com/fvv/bookstore/view/OrderViewImpl.java
> +		final List<OrderItem> items = new ArrayList<OrderItem>();
ok

2018-04-29 16:28 UTC, fvv-vasquez commented on src/main/java/com/fvv/bookstore/view/OrderViewImpl.java
> +			final Book book = this.bookController.findBookByTitle(
ok

2018-04-29 16:29 UTC, fvv-vasquez commented on src/main/java/com/fvv/bookstore/view/OrderViewImpl.java
> +			final Cellphone cellphone = this.cellphoneController.findCellphoneByBrand(
ok

2018-04-29 16:29 UTC, fvv-vasquez commented on src/main/java/com/fvv/bookstore/view/OrderViewImpl.java
> +			final Dvd dvd = this.dvdController.findDvdByTitle(
ok

2018-04-29 16:29 UTC, fvv-vasquez commented on src/main/java/com/fvv/bookstore/view/OrderViewImpl.java
> +			final Laptop laptop = this.laptopController.findLaptopByBrand(
ok

2018-04-29 16:30 UTC, fvv-vasquez commented on src/main/java/com/fvv/bookstore/view/OrderViewImpl.java
> +			final Magazine magazine = this.magazineController.findMagazineByName(
ok

2018-04-29 16:39 UTC, fvv-vasquez commented on src/main/java/com/fvv/bookstore/view/OrderViewImpl.java
> +	private Magazine findMagazineByName() {
ok

2018-04-29 16:40 UTC, fvv-vasquez commented on src/main/java/com/fvv/bookstore/view/OrderViewImpl.java
> +	private Laptop findLaptopByBrand() {
ok

2018-04-29 16:41 UTC, fvv-vasquez commented on src/main/java/com/fvv/bookstore/view/OrderViewImpl.java
> +	private Dvd findDvdByTitle() {
ok

2018-04-29 16:42 UTC, fvv-vasquez commented on src/main/java/com/fvv/bookstore/view/OrderViewImpl.java
> +	private Cellphone findCellphoneByBrand() {
ok

2018-04-29 16:43 UTC, fvv-vasquez commented on src/main/java/com/fvv/bookstore/view/OrderViewImpl.java
> +	private Book findBookByTitle() {
ok

2018-04-29 16:45 UTC, fvv-vasquez commented on src/main/java/com/fvv/bookstore/view/OrderViewImpl.java
> +	 * @return a boolean.
ok

2018-04-29 16:46 UTC, fvv-vasquez commented on src/main/java/com/fvv/bookstore/view/OrderViewImpl.java
> +	private List<OrderItem> createOrderItemFromInput() throws ControllerException {
ok

2018-04-29 22:16 UTC, fvv-vasquez commented on src/main/java/com/fvv/bookstore/view/OrderViewImpl.java
> +							if(book.getStockQty() > 0) {
ok

2018-04-29 22:54 UTC, cssantos0 approved these changes
very good job

2018-04-29 22:55 UTC, merged